### ISSUE TITLE
Create uberjar to consume lemminx-maven extension in vscode

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx-maven#120]
Create uberjar to consume lemminx-maven extension in vscode

**Comment by fbricon** [comment]
I'm going to ban you from GitHub for the rest of your PTO

**Comment by angelozerr** [comment]
> I'm going to ban you from GitHub for the rest of your PTO

You are my angel @fbricon  :)

**Comment by mickaelistria** [comment]
@angelozerr any progress or issue with this topic?

**Comment by angelozerr** [comment]
> @angelozerr any progress or issue with this topic?

No, but to test this PR in vscode (but it doesn't work), 

 * build the uber JAR.
 * import https://github.com/angelozerr/vscode-xml-maven
 * copy/paste the JAR into https://github.com/angelozerr/vscode-xml-maven/tree/master/jar
 * replace https://github.com/angelozerr/vscode-xml-maven/blob/62b04bd2f184186efcf316e52e88d011aea4c277/package.json#L19 with the proper path of the JAR
 * open the vscode-xml-maven into vscode and start the project.
 * disable vscode-maven
 * open a pom.xml  and try to have completion on dependency, it doesn't work.

**Comment by mickaelistria** [comment]
Does LemMinX have some logging to list available extensions and their loading status?

**Comment by Eskibear** [comment]
I don't have much context info, but simply want to try lemminx-maven with vscode. As mentioned above in https://github.com/eclipse/lemminx-maven/issues/120#issuecomment-683820714 , I was not able to enable it in vscode either.

**I don't know where to get the correct jar to use.** In package.json I tried to specify `xml.javaExtensions` with several jars, but none was working.
1. `lemminx-maven-0.1.1-SNAPSHOT.jar` compiled by command `mvn clean package`, based on branch`angelozerr/uber-jar`. See below:

<details><summary>error log</summary>

[Error - 2:00:22 PM] Sep 01, 2020 02:00:22 org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError()
Message: Internal error: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1238)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at org.eclipse.lemminx.maven.MavenPlugin.newPlexusContainer(MavenPlugin.java:204)
	at org.eclipse.lemminx.maven.MavenPlugin.initialize(MavenPlugin.java:118)
	at org.eclipse.lemminx.maven.MavenPlugin.start(MavenPlugin.java:105)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.registerExtension(XMLExtensionsRegistry.java:199)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.lambda$initialize$2(XMLExtensionsRegistry.java:191)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initialize(XMLExtensionsRegistry.java:190)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initializeIfNeeded(XMLExtensionsRegistry.java:180)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.getCompletionParticipants(XMLExtensionsRegistry.java:122)
	at org.eclipse.lemminx.services.XMLCompletions.getCompletionParticipants(XMLCompletions.java:935)
	at org.eclipse.lemminx.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:625)
	at org.eclipse.lemminx.services.XMLCompletions.collectInsideContent(XMLCompletions.java:752)
	at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:243)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:145)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$completion$1(XMLTextDocumentService.java:192)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	... 7 more

[Error - 2:00:22 PM] Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1238)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at org.eclipse.lemminx.maven.MavenPlugin.newPlexusContainer(MavenPlugin.java:204)
	at org.eclipse.lemminx.maven.MavenPlugin.initialize(MavenPlugin.java:118)
	at org.eclipse.lemminx.maven.MavenPlugin.start(MavenPlugin.java:105)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.registerExtension(XMLExtensionsRegistry.java:199)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.lambda$initialize$2(XMLExtensionsRegistry.java:191)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initialize(XMLExtensionsRegistry.java:190)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initializeIfNeeded(XMLExtensionsRegistry.java:180)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.getCompletionParticipants(XMLExtensionsRegistry.java:122)
	at org.eclipse.lemminx.services.XMLCompletions.getCompletionParticipants(XMLCompletions.java:935)
	at org.eclipse.lemminx.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:625)
	at org.eclipse.lemminx.services.XMLCompletions.collectInsideContent(XMLCompletions.java:752)
	at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:243)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:145)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$completion$1(XMLTextDocumentService.java:192)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	... 7 more

[Error - 2:00:23 PM] Sep 01, 2020 02:00:23 org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError()
Message: Internal error: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1238)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at org.eclipse.lemminx.maven.MavenPlugin.newPlexusContainer(MavenPlugin.java:204)
	at org.eclipse.lemminx.maven.MavenPlugin.initialize(MavenPlugin.java:118)
	at org.eclipse.lemminx.maven.MavenPlugin.start(MavenPlugin.java:105)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.registerExtension(XMLExtensionsRegistry.java:199)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.lambda$initialize$2(XMLExtensionsRegistry.java:191)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initialize(XMLExtensionsRegistry.java:190)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initializeIfNeeded(XMLExtensionsRegistry.java:180)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.getDocumentLinkParticipants(XMLExtensionsRegistry.java:142)
	at org.eclipse.lemminx.services.XMLDocumentLink.findDocumentLinks(XMLDocumentLink.java:37)
	at org.eclipse.lemminx.services.XMLLanguageService.findDocumentLinks(XMLLanguageService.java:230)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$documentLink$11(XMLTextDocumentService.java:327)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	... 7 more

[Error - 2:00:23 PM] Request textDocument/documentLink failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1238)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at org.eclipse.lemminx.maven.MavenPlugin.newPlexusContainer(MavenPlugin.java:204)
	at org.eclipse.lemminx.maven.MavenPlugin.initialize(MavenPlugin.java:118)
	at org.eclipse.lemminx.maven.MavenPlugin.start(MavenPlugin.java:105)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.registerExtension(XMLExtensionsRegistry.java:199)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.lambda$initialize$2(XMLExtensionsRegistry.java:191)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initialize(XMLExtensionsRegistry.java:190)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initializeIfNeeded(XMLExtensionsRegistry.java:180)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.getDocumentLinkParticipants(XMLExtensionsRegistry.java:142)
	at org.eclipse.lemminx.services.XMLDocumentLink.findDocumentLinks(XMLDocumentLink.java:37)
	at org.eclipse.lemminx.services.XMLLanguageService.findDocumentLinks(XMLLanguageService.java:230)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$documentLink$11(XMLTextDocumentService.java:327)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	... 7 more

</details>


2. [lemminx-maven-0.1.0.jar](https://repo.eclipse.org/content/repositories/lemminx-releases/org/eclipse/lemminx/lemminx-maven/0.1.0/) downloaded from repo.eclipse.org, I got below error:
<details><summary>error log</summary>
[Error - 1:47:44 PM] Sep 01, 2020 01:47:44 org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError()
Message: Internal error: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1238)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at org.eclipse.lemminx.maven.MavenPlugin.newPlexusContainer(MavenPlugin.java:204)
	at org.eclipse.lemminx.maven.MavenPlugin.initialize(MavenPlugin.java:118)
	at org.eclipse.lemminx.maven.MavenPlugin.start(MavenPlugin.java:105)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.registerExtension(XMLExtensionsRegistry.java:199)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.lambda$initialize$2(XMLExtensionsRegistry.java:191)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initialize(XMLExtensionsRegistry.java:190)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initializeIfNeeded(XMLExtensionsRegistry.java:180)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.getCompletionParticipants(XMLExtensionsRegistry.java:122)
	at org.eclipse.lemminx.services.XMLCompletions.getCompletionParticipants(XMLCompletions.java:935)
	at org.eclipse.lemminx.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:625)
	at org.eclipse.lemminx.services.XMLCompletions.collectInsideContent(XMLCompletions.java:752)
	at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:243)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:145)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$completion$1(XMLTextDocumentService.java:192)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	... 7 more

[Error - 1:47:44 PM] Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1238)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at org.eclipse.lemminx.maven.MavenPlugin.newPlexusContainer(MavenPlugin.java:204)
	at org.eclipse.lemminx.maven.MavenPlugin.initialize(MavenPlugin.java:118)
	at org.eclipse.lemminx.maven.MavenPlugin.start(MavenPlugin.java:105)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.registerExtension(XMLExtensionsRegistry.java:199)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.lambda$initialize$2(XMLExtensionsRegistry.java:191)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initialize(XMLExtensionsRegistry.java:190)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initializeIfNeeded(XMLExtensionsRegistry.java:180)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.getCompletionParticipants(XMLExtensionsRegistry.java:122)
	at org.eclipse.lemminx.services.XMLCompletions.getCompletionParticipants(XMLCompletions.java:935)
	at org.eclipse.lemminx.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:625)
	at org.eclipse.lemminx.services.XMLCompletions.collectInsideContent(XMLCompletions.java:752)
	at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:243)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:145)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$completion$1(XMLTextDocumentService.java:192)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	... 7 more

[Error - 1:47:45 PM] Sep 01, 2020 01:47:45 org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError()
Message: Internal error: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1238)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at org.eclipse.lemminx.maven.MavenPlugin.newPlexusContainer(MavenPlugin.java:204)
	at org.eclipse.lemminx.maven.MavenPlugin.initialize(MavenPlugin.java:118)
	at org.eclipse.lemminx.maven.MavenPlugin.start(MavenPlugin.java:105)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.registerExtension(XMLExtensionsRegistry.java:199)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.lambda$initialize$2(XMLExtensionsRegistry.java:191)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initialize(XMLExtensionsRegistry.java:190)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initializeIfNeeded(XMLExtensionsRegistry.java:180)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.getDocumentLinkParticipants(XMLExtensionsRegistry.java:142)
	at org.eclipse.lemminx.services.XMLDocumentLink.findDocumentLinks(XMLDocumentLink.java:37)
	at org.eclipse.lemminx.services.XMLLanguageService.findDocumentLinks(XMLLanguageService.java:230)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$documentLink$11(XMLTextDocumentService.java:327)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	... 7 more

[Error - 1:47:45 PM] Request textDocument/documentLink failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1238)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/ClassWorld
	at org.eclipse.lemminx.maven.MavenPlugin.newPlexusContainer(MavenPlugin.java:204)
	at org.eclipse.lemminx.maven.MavenPlugin.initialize(MavenPlugin.java:118)
	at org.eclipse.lemminx.maven.MavenPlugin.start(MavenPlugin.java:105)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.registerExtension(XMLExtensionsRegistry.java:199)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.lambda$initialize$2(XMLExtensionsRegistry.java:191)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initialize(XMLExtensionsRegistry.java:190)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initializeIfNeeded(XMLExtensionsRegistry.java:180)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.getDocumentLinkParticipants(XMLExtensionsRegistry.java:142)
	at org.eclipse.lemminx.services.XMLDocumentLink.findDocumentLinks(XMLDocumentLink.java:37)
	at org.eclipse.lemminx.services.XMLLanguageService.findDocumentLinks(XMLLanguageService.java:230)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$documentLink$11(XMLTextDocumentService.java:327)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	... 7 more

</details>


I guess neither of the above (1 & 2) is uber jar. 

3. [org.eclipse.lemminx-0.13.1-uber.jar](https://repo.eclipse.org/content/repositories/lemminx-releases/org/eclipse/lemminx/org.eclipse.lemminx/0.13.1/) downloaded from repo.eclipse.org. No error in output window, but also no suggestion for dependencies.  
So I assume this one is lemminx itself instead of lemminx-maven extension.

**Comment by mickaelistria** [comment]
I'm not much familiar with how vscode-xml works, but I imagine if you want LemMinX-Maven to be an extension of the LemMinX one (and not duplicate it), you'll need to have the uber-jar containing lemminx-maven + all its dependencies (maven, plexus...) - everything that's already in lemminx "core".
But one possible issue is that Maven relies a lot on dependency injection and probably on some metadata files, which might be overriden if you build an uber-jar.
So one working approach (that's used in Eclipse IDE), is that instead of generating a uber-jar, you generate a set of jars and pass those jars as classpath extension when starting lemminx.

**Comment by angelozerr** [comment]
> 'm not much familiar with how vscode-xml works, but I imagine if you want LemMinX-Maven to be an extension of the LemMinX one (and not duplicate it), you'll need to have the uber-jar containing lemminx-maven + all its dependencies (maven, plexus...) - everything that's already in lemminx "core".

Indeed my work on uber JAR tries to do that, but I think it misses something.

> But one possible issue is that Maven relies a lot on dependency injection and probably on some metadata files, which might be overriden if you build an uber-jar.

Perhaps it's the problem?

> So one working approach (that's used in Eclipse IDE), is that instead of generating a uber-jar, you generate a set of jars and pass those jars as classpath extension when starting lemminx.

We can do that too, but the question is how to get the full list of required JARs? It seems the integration of lemminx-maven in Eclipse IDE uses `BundleResolver.getBundleResource`
https://github.com/eclipse/m2e-core/blob/d53d22d98f2ac6d1f7124e146df8ed6fb22f6a75/org.eclipse.m2e.editor.lemminx/src/org/eclipse/m2e/editor/lemminx/MavenRuntimeClasspathProvider.java#L56 

If we could do the same thing with pom.xml maven to start a goal and extract this ful  JARs list it should be fine. I don't know how to do that.

**Comment by mickaelistria** [comment]
I think instead of shading all the dependencies into a single jar, it's possible to create a maven assembly that would create a zip consisting of lemminx-maven and deps and exclude lemminx and transitive deps.

**Comment by mickaelistria** [comment]
Isn't this story covered by https://github.com/eclipse/lemminx-maven/commit/3c70e7be367d8ebb8922033a4d367bd44f554b96 ? If so, can we close?

**Comment by angelozerr** [comment]
> Isn't this story covered by 3c70e7b ? If so, can we close?

Indeed, we can close it.
