### ISSUE TITLE
MavenLemminxExtension.match fails if file URI is not hierarchical

### ISSUE THREAD

**Issue by fbricon** [eclipse/lemminx-maven#137]
Trying to integrate lemminx-maven in vscode, when you create a new unsaved empty file, set to use XML, completion on `<` fails with:
```
[Trace - 5:01:52 PM] Sending request 'textDocument/completion - (31)'.
Params: {
    "textDocument": {
        "uri": "untitled:Untitled-1"
    },
    "position": {
        "line": 27,
        "character": 7
    },
    "context": {
        "triggerKind": 1
    }
}


[Trace - 5:01:53 PM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "Sep. 07, 2020 05:01:52 org.eclipse.lemminx.services.XMLCompletions collectOpenTagSuggestions()\nMessage: While performing ICompletionParticipant#onTagOpen\njava.lang.IllegalArgumentException: URI is not hierarchical\n\tat java.base/java.io.File.<init>(File.java:420)\n\tat org.eclipse.lemminx.maven.MavenLemminxExtension.match(MavenLemminxExtension.java:263)\n\tat org.eclipse.lemminx.maven.MavenCompletionParticipant.onTagOpen(MavenCompletionParticipant.java:105)\n\tat org.eclipse.lemminx.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:627)\n\tat org.eclipse.lemminx.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:601)\n\tat org.eclipse.lemminx.services.XMLCompletions.collectTagSuggestions(XMLCompletions.java:593)\n\tat org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:104)\n\tat org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:145)\n\tat org.eclipse.lemminx.XMLTextDocumentService.lambda$completion$1(XMLTextDocumentService.java:192)\n\tat java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)\n\tat java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)\n\tat java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)\n"
}


[Error - 5:01:53 PM] Sep. 07, 2020 05:01:52 org.eclipse.lemminx.services.XMLCompletions collectOpenTagSuggestions()
Message: While performing ICompletionParticipant#onTagOpen
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(File.java:420)
	at org.eclipse.lemminx.maven.MavenLemminxExtension.match(MavenLemminxExtension.java:263)
	at org.eclipse.lemminx.maven.MavenCompletionParticipant.onTagOpen(MavenCompletionParticipant.java:105)
	at org.eclipse.lemminx.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:627)
	at org.eclipse.lemminx.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:601)
	at org.eclipse.lemminx.services.XMLCompletions.collectTagSuggestions(XMLCompletions.java:593)
	at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:104)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:145)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$completion$1(XMLTextDocumentService.java:192)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

at the very least, it should ignore the unsupported URI and not throw any exception.

**Comment by mickaelistria** [comment]
Attempt to fix with https://github.com/eclipse/lemminx-maven/pull/139

**Comment by mickaelistria** [comment]
PR merged, issue fixed.
