### ISSUE TITLE
Typing `<` on standalone pom.xml throws XmlPullParserException

### ISSUE THREAD

**Issue by fbricon** [eclipse/lemminx-maven#138]
Testing lemminx-maven in vscode. Open a random pom.xml, type `<`
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>foo.bar</groupId>
	<artifactId>kjh</artifactId>
	<version>0.0.1-SNAPSHOT</version>
    <
</project>
```
look at the log:
```
org.codehaus.plexus.util.xml.pull.XmlPullParserException: unexpected character in markup \n (position: END_TAG seen ...<version>0.0.1-SNAPSHOT</version>\n    <\n... @9:1) 
	at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1525)
	at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1319)
	at org.codehaus.plexus.util.xml.pull.MXParser.nextTag(MXParser.java:1302)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseModel(MavenXpp3Reader.java:2072)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:3872)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:595)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:609)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:638)
	at org.eclipse.lemminx.maven.MavenProjectCache.parseAndCache(MavenProjectCache.java:156)
	at org.eclipse.lemminx.maven.MavenProjectCache.check(MavenProjectCache.java:108)
	at org.eclipse.lemminx.maven.MavenProjectCache.getProblemsFor(MavenProjectCache.java:101)
	at org.eclipse.lemminx.maven.MavenDiagnosticParticipant.doDiagnostics(MavenDiagnosticParticipant.java:48)
	at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:85)
	at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:53)
	at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:159)
	at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:168)
	at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:466)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$triggerValidationFor$23(XMLTextDocumentService.java:459)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Completion is not available at that point, it should propose all elements from the maven xsd.

**Comment by mickaelistria** [comment]
This stack is "only" logged and doesn't interrupt behavior.
I tried you example with m2e, and I get the XSD completion.
I'm closing it as it's actually a request for better logging, which is already tracked by #134 .
