### ISSUE TITLE
high CPU consumption

### ISSUE THREAD

**Issue by martinlippert** [eclipse/lemminx-maven#151]
Since we integrated the Wild Web Developer bundle into the Spring Tools distribution, we had a few people reporting that something causes a high CPU consumption Diving deeper, users reported that the XML language server process was burning quite a lot of CPU cycles.

I am not sure what exactly causes this and we haven't been able to create a reproducable scenario, one colleague took a thread dump of the process and that points into the direction of the maven extension for the XML language server.

This is the "interesting" piece from the thread dump:

```
"ForkJoinPool.commonPool-worker-7" #20 daemon prio=5 os_prio=31 cpu=377433.58ms elapsed=497.03s tid=0x00007fc342224800 nid=0x6903 runnable  [0x000070000e9b1000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.force0(java.base@14.0.2/Native Method)
	at sun.nio.ch.FileDispatcherImpl.force(java.base@14.0.2/FileDispatcherImpl.java:82)
	at sun.nio.ch.FileChannelImpl.force(java.base@14.0.2/FileChannelImpl.java:467)
	at org.apache.lucene.util.IOUtils.fsync(IOUtils.java:392)
	at org.apache.lucene.store.FSDirectory.fsync(FSDirectory.java:288)
	at org.apache.lucene.store.FSDirectory.sync(FSDirectory.java:232)
	at org.apache.lucene.store.LockValidatingDirectoryWrapper.sync(LockValidatingDirectoryWrapper.java:62)
	at org.apache.lucene.index.IndexWriter.startCommit(IndexWriter.java:4446)
	at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2865)
	- locked <0x000000073626e968> (a java.lang.Object)
	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:2970)
	- locked <0x000000073626e968> (a java.lang.Object)
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:2935)
	at org.apache.maven.index.context.DefaultIndexingContext.storeDescriptor(DefaultIndexingContext.java:375)
	at org.apache.maven.index.context.DefaultIndexingContext.replace(DefaultIndexingContext.java:637)
	- locked <0x00000007023e1b98> (a org.apache.maven.index.context.DefaultIndexingContext)
	at org.apache.maven.index.updater.DefaultIndexUpdater.loadIndexDirectory(DefaultIndexUpdater.java:225)
	at org.apache.maven.index.updater.DefaultIndexUpdater.access$300(DefaultIndexUpdater.java:76)
	at org.apache.maven.index.updater.DefaultIndexUpdater$LuceneIndexAdaptor.setIndexFile(DefaultIndexUpdater.java:518)
	at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:736)
	at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:161)
	at org.eclipse.lemminx.maven.searcher.RemoteRepositoryIndexSearcher.lambda$updateIndex$6(RemoteRepositoryIndexSearcher.java:239)
	at org.eclipse.lemminx.maven.searcher.RemoteRepositoryIndexSearcher$$Lambda$132/0x0000000800db2440.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(java.base@14.0.2/CompletableFuture.java:1800)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(java.base@14.0.2/CompletableFuture.java:1792)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@14.0.2/ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@14.0.2/ForkJoinPool.java:1016)
	at java.util.concurrent.ForkJoinPool.scan(java.base@14.0.2/ForkJoinPool.java:1665)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@14.0.2/ForkJoinPool.java:1598)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@14.0.2/ForkJoinWorkerThread.java:183)
```

Everything else looks unsuspicious. If you want to take a look at the rest of the thread dump, let me know, I can attach it, too.

Hope you can help here and maybe have an idea what causes this high CPU usage. It seems to annoy users quite a bit.

**Comment by mickaelistria** [comment]
Dup of #98.
