### ISSUE TITLE
jacoco-maven-plugin cannot be resolved

### ISSUE THREAD

**Issue by rbioteau** [eclipse/lemminx-maven#164]
Hi !
When resolving the `jacoco-maven-plugin`, errors are thrown during the plugin resolution:

```
[ERROR] Failed to determine Java version for profile maven-jdk9 @ org.jacoco:org.jacoco.build:0.8.6
[ERROR] Failed to determine Java version for profile maven-jdk12 @ org.jacoco:org.jacoco.build:0.8.6
```
I guess it is because I do not have a jdk9 or jdk12 installed or configured in toolchains.
But the root cause is not displayed in the warning logged in the Problem view. I only have this misleading message:

```
Plugin could not be resolved. Ensure the plugin's groupId, artifactId and version are present.

Additional information: Plugin org.jacoco:jacoco-maven-plugin:0.8.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.jacoco:jacoco-maven-plugin:jar:0.8.6
```
Should the `validatePluginResolution` ignore those kind of errors ? By the way, the language server completion does not work properly for this plugin.

Full stacktrace:
```
org.apache.maven.plugin.PluginResolutionException: Plugin org.jacoco:jacoco-maven-plugin:0.8.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.jacoco:jacoco-maven-plugin:jar:0.8.6
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:120)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor(DefaultMavenPluginManager.java:182)
	at org.eclipse.lemminx.maven.MavenPluginUtils.getContainingPluginDescriptor(MavenPluginUtils.java:192)
	at org.eclipse.lemminx.maven.PluginValidator.validatePluginResolution(PluginValidator.java:49)
	at org.eclipse.lemminx.maven.PluginValidator.validateGoal(PluginValidator.java:112)
	at org.eclipse.lemminx.maven.MavenDiagnosticParticipant.doDiagnostics(MavenDiagnosticParticipant.java:73)
	at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:85)
	at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:53)
	at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:152)
	at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:161)
	at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:464)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$triggerValidationFor$23(XMLTextDocumentService.java:457)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.jacoco:jacoco-maven-plugin:jar:0.8.6
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:310)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:255)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:106)
	... 18 more
Caused by: org.apache.maven.model.building.ModelBuildingException: 2 problems were encountered while building the effective model for org.jacoco:jacoco-maven-plugin:0.8.6
[ERROR] Failed to determine Java version for profile maven-jdk9 @ org.jacoco:org.jacoco.build:0.8.6
[ERROR] Failed to determine Java version for profile maven-jdk12 @ org.jacoco:org.jacoco.build:0.8.6

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:498)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:440)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:430)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:292)
	... 21 more
org.apache.maven.plugin.PluginResolutionException: Plugin org.jacoco:jacoco-maven-plugin:0.8.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.jacoco:jacoco-maven-plugin:jar:0.8.6
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:120)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor(DefaultMavenPluginManager.java:182)
	at org.eclipse.lemminx.maven.MavenPluginUtils.getContainingPluginDescriptor(MavenPluginUtils.java:192)
	at org.eclipse.lemminx.maven.PluginValidator.validatePluginResolution(PluginValidator.java:49)
	at org.eclipse.lemminx.maven.PluginValidator.validateConfiguration(PluginValidator.java:79)
	at org.eclipse.lemminx.maven.MavenDiagnosticParticipant.doDiagnostics(MavenDiagnosticParticipant.java:73)
	at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:85)
	at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:53)
	at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:152)
	at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:161)
	at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:464)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$triggerValidationFor$23(XMLTextDocumentService.java:457)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.jacoco:jacoco-maven-plugin:jar:0.8.6
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:310)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:255)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:106)
	... 18 more
Caused by: org.apache.maven.model.building.ModelBuildingException: 2 problems were encountered while building the effective model for org.jacoco:jacoco-maven-plugin:0.8.6
[ERROR] Failed to determine Java version for profile maven-jdk9 @ org.jacoco:org.jacoco.build:0.8.6
[ERROR] Failed to determine Java version for profile maven-jdk12 @ org.jacoco:org.jacoco.build:0.8.6

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:498)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:440)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:430)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:292)
	... 21 more
```

HTH  
Romain

**Comment by mickaelistria** [comment]
Hi Romain!
Can you please share a minimal project that can reproduce this issue?

**Comment by rbioteau** [comment]
See https://github.com/eclipse/lemminx-maven/pull/169

**Comment by rbioteau** [comment]
After trying to write a test, I found at that https://github.com/eclipse/lemminx-maven/commit/d626869e57787166008d2a098524e408a0fc3dbd fixes the issues

**Comment by mickaelistria** [comment]
If you can still contribute the unit test, that would be very welcome!

**Comment by rbioteau** [comment]
Why not. Currently the master branch build seems broken.

**Comment by mickaelistria** [comment]
there is indeed an issue with completion tests, I'll look at it. But I think you can work on a new test without having to run the completion tests anyway (starting your specific test from the IDE or with `-Dtest=` option of maven-surefire-plugin).

**Comment by rbioteau** [comment]
https://github.com/eclipse/lemminx-maven/pull/171
