### ISSUE TITLE
NPE in PluginValidator.validatePluginResolution

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx-maven#185]
Given this pom.xml:

```xml
<project 
		xmlns="http://maven.apache.org/POM/4.0.0"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.eclipse.lemminx</groupId>
	<artifactId>lemminx-parent</artifactId>
	<version>0.13.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<description>LemMinX is a XML Language Server Protocol (LSP), and can be used with any editor that supports LSP, to offer an outstanding XML editing experience</description>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<lsp4j.version>0.9.0</lsp4j.version>
		<junit.version>5.6.1</junit.version>
	</properties>
	<url>https://github.com/eclipse/lemminx</url>
	<licenses>
		<license>
			<name>Eclipse Public License - v 2.0</name>
			<url>http://www.eclipse.org/legal/epl-v20.html</url>
			<distribution>repo</distribution>
		</license>
	</licenses>
	<scm>
		<connection>scm:git:git@github.com:eclipse/lemminx.git</connection>
		<developerConnection>scm:git:git@github.com:eclipse/lemminx.git</developerConnection>
		<url>https://github.com/eclipse/lemminx</url>
		<tag>HEAD</tag>
	</scm>
	<modules>
		<module>org.eclipse.lemminx</module>
	</modules>
	<pluginRepositories>
		<pluginRepository>
			<id>cbi-release</id>
			<url>https://repo.eclipse.org/content/repositories/cbi-releases/</url>
		</pluginRepository>
	</pluginRepositories>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.google.code.gson</groupId>
				<artifactId>gson</artifactId>
				<version>2.7</version>
			</dependency>
			<dependency>
				<groupId>org.eclipse.lsp4j</groupId>
				<artifactId>org.eclipse.lsp4j</artifactId>
				<version>${lsp4j.version}</version>
			</dependency>
			<dependency>
				<groupId>org.eclipse.lsp4j</groupId>
				<artifactId>org.eclipse.lsp4j.jsonrpc</artifactId>
				<version>${lsp4j.version}</version>
			</dependency>
			<dependency>
				<groupId>org.eclipse.xtend</groupId>
				<artifactId>org.eclipse.xtend.lib</artifactId>
				<version>2.16.0.M1</version>
			</dependency>
			<dependency>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter-api</artifactId>
				<version>${junit.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter-engine</artifactId>
				<version>${junit.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter-params</artifactId>
				<version>${junit.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.eclipse</groupId>
				<artifactId>org.eclipse.lemminx</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.8.0</version>
					<configuration>
						<source>1.8</source>
						<target>1.8</target>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>3.0.0-M4</version>
					<configuration>
						<runOrder>random</runOrder>
						<statelessTestsetReporter implementation="org.apache.maven.plugin.surefire.extensions.junit5.JUnit5Xml30StatelessReporter">
							<disable>false</disable>
							<usePhrasedFileName>false</usePhrasedFileName>
							<usePhrasedTestSuiteClassName>false</usePhrasedTestSuiteClassName>
							<usePhrasedTestCaseClassName>false</usePhrasedTestCaseClassName>
							<usePhrasedTestCaseMethodName>true</usePhrasedTestCaseMethodName>
						</statelessTestsetReporter>
						<consoleOutputReporter implementation="org.apache.maven.plugin.surefire.extensions.junit5.JUnit5ConsoleOutputReporter">
							<disable>false</disable>
							<encoding>UTF-8</encoding>
							<usePhrasedFileName>false</usePhrasedFileName>
						</consoleOutputReporter>
						<statelessTestsetInfoReporter implementation="org.apache.maven.plugin.surefire.extensions.junit5.JUnit5StatelessTestsetInfoReporter">
							<disable>false</disable>
							<usePhrasedFileName>false</usePhrasedFileName>
							<usePhrasedClassNameInRunning>true</usePhrasedClassNameInRunning>
							<usePhrasedClassNameInTestCaseSummary>false</usePhrasedClassNameInTestCaseSummary>
						</statelessTestsetInfoReporter>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>3.1.1</version>
					<configuration>
						<archive>
							<manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
						</archive>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.felix</groupId>
					<artifactId>maven-bundle-plugin</artifactId>
					<version>4.1.0</version>
					<executions>
						<execution>
							<id>bundle-manifest</id>
							<phase>process-classes</phase>
							<goals>
								<goal>manifest</goal>
							</goals>
							<configuration>
								<instructions>
									<Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
								</instructions>
							</configuration>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-release-plugin</artifactId>
					<version>3.0.0-M1</version>
					<configuration>
						<tagNameFormat>@{project.version}</tagNameFormat>
						<arguments>-DskipTests=true -Dcbi.jarsigner.skip=false -Pci,generate-p2</arguments>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
	<distributionManagement>
		<repository>
			<id>repo.eclipse.org</id>
			<name>lemminx-releases</name>
			<url>https://repo.eclipse.org/content/repositories/lemminx-releases/</url>
		</repository>
		<snapshotRepository>
			<id>repo.eclipse.org</id>
			<name>lemminx-snapshots</name>
			<url>https://repo.eclipse.org/content/repositories/lemminx-snapshots/</url>
		</snapshotRepository>
	</distributionManagement>
	<profiles>
		<profile>
			<id>ci</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-source-plugin</artifactId>
						<version>3.0.1</version>
						<executions>
							<execution>
								<id>attach-sources</id>
								<phase>package</phase>
								<goals>
									<goal>jar</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-javadoc-plugin</artifactId>
						<version>3.0.1</version>
						<executions>
							<execution>
								<id>attach-javadocs</id>
								<phase>package</phase>
								<goals>
									<goal>jar</goal>
								</goals>
							</execution>
						</executions>
						<configuration>
							<doclint>none</doclint>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>generate-p2</id>
			<build>
				<pluginManagement>
					<plugins>
						<plugin>
							<groupId>org.eclipse.tycho.extras</groupId>
							<artifactId>tycho-eclipserun-plugin</artifactId>
							<version>1.3.0</version>
							<executions>
								<execution>
									<id>generate-p2-site</id>
									<phase>package</phase>
									<goals>
										<goal>eclipse-run</goal>
									</goals>
									<configuration>
										<executionEnvironment>JavaSE-1.8</executionEnvironment>
										<repositories>
											<repository>
												<id>eclipse-4.10</id>
												<layout>p2</layout>
												<url>http://download.eclipse.org/eclipse/updates/4.10/R-4.10-201812060815/</url>
											</repository>
										</repositories>
										<dependencies>
											<dependency>
												<artifactId>org.eclipse.equinox.p2.publisher.eclipse</artifactId>
												<type>eclipse-plugin</type>
											</dependency>
											<dependency>
												<artifactId>org.eclipse.equinox.p2.core.feature</artifactId>
												<type>eclipse-feature</type>
											</dependency>
											<dependency>
												<artifactId>org.eclipse.equinox.core.feature</artifactId>
												<type>eclipse-feature</type>
											</dependency>
										</dependencies>
										<applicationsArgs>
											<arg>-application</arg>
											<arg>org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher</arg>
											<arg>-metadataRepository</arg>
											<arg>file:${project.build.directory}/p2</arg>
											<arg>-artifactRepository</arg>
											<arg>file:${project.build.directory}/p2</arg>
											<arg>-bundles</arg>
											<arg>${project.build.directory}</arg>
											<arg>-compress</arg>
											<arg>-publishArtifacts</arg>
										</applicationsArgs>
									</configuration>
								</execution>
							</executions>
						</plugin>
					</plugins>
				</pluginManagement>
			</build>
		</profile>
	</profiles>
</project>
```

Open completion, you will see the following NPE:

```
[Error - 17:12:47] Jan 09, 2021 05:12:47 org.eclipse.lemminx.services.XMLDiagnostics doExtensionsDiagnostics()
Message: Error while processing diagnostics for the participant 'org.eclipse.lemminx.extensions.maven.MavenDiagnosticParticipant'.
java.lang.NullPointerException
	at org.eclipse.lemminx.extensions.maven.PluginValidator.validatePluginResolution(PluginValidator.java:43)
	at org.eclipse.lemminx.extensions.maven.PluginValidator.validateConfiguration(PluginValidator.java:71)
	at org.eclipse.lemminx.extensions.maven.MavenDiagnosticParticipant.doDiagnostics(MavenDiagnosticParticipant.java:62)
	at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:64)
	at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:46)
	at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:161)
	at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:170)
	at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:512)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$triggerValidationFor$26(XMLTextDocumentService.java:505)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by mickaelistria** [comment]
This is supposed to be fixed since January ;)
