### ISSUE TITLE
POM editor freezing

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx-maven#241]
with the latest snapshot the editor is freezing when every trying to change some auto completable section like project properties.

```
"main" #1 prio=6 os_prio=0 cpu=24390.62ms elapsed=576.28s tid=0x0000024418fc0860 nid=0x8cb4 waiting on condition  [0x000000dc0b3db000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@16.0.1/Native Method)
        - parking to wait for  <0x00000000b1723b18> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(java.base@16.0.1/LockSupport.java:211)
        at java.util.concurrent.CompletableFuture$Signaller.block(java.base@16.0.1/CompletableFuture.java:1860)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@16.0.1/ForkJoinPool.java:3137)
        at java.util.concurrent.CompletableFuture.waitingGet(java.base@16.0.1/CompletableFuture.java:1894)
        at java.util.concurrent.CompletableFuture.get(java.base@16.0.1/CompletableFuture.java:2068)
        at org.eclipse.lsp4e.operations.linkedediting.LSPLinkedEditingAutoEditStrategy.customizeDocumentCommand(LSPLinkedEditingAutoEditStrategy.java:41)
        at org.eclipse.jface.text.TextViewer.customizeDocumentCommand(TextViewer.java:3698)
        at org.eclipse.jface.text.TextViewer.handleVerifyEvent(TextViewer.java:3740)
        at org.eclipse.jface.text.source.projection.ProjectionViewer.handleVerifyEvent(ProjectionViewer.java:1248)
        at org.eclipse.jface.text.TextViewer$TextVerifyListener.verifyText(TextViewer.java:426)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:277)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1069)
        at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:773)
        at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7607)
        at org.eclipse.swt.custom.StyledText.sendKeyEvent(StyledText.java:8539)
        at org.eclipse.swt.custom.StyledText.doBackspace(StyledText.java:2340)
        at org.eclipse.swt.custom.StyledText.invokeAction(StyledText.java:7428)
        at org.eclipse.swt.custom.StyledText.handleKey(StyledText.java:6226)
        at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6253)
        at org.eclipse.swt.custom.StyledText.lambda$28(StyledText.java:5932)
        at org.eclipse.swt.custom.StyledText$$Lambda$243/0x0000000800e91eb8.handleEvent(Unknown Source)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1069)
        at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1111)
        at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1107)
        at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1536)
        at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4875)
        at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:345)
        at org.ec
```

Updating the WildWebDeveloper XMLTools to latest snapshot version solves the issue.

**Comment by gayanper** [comment]
Spoke too soon, the problem is there even after using latest snapshot of XML language server. The problem happened when tried to copy the following property

`<maven.compiler.target>1.8</maven.compiler.target>
`
and trying to change it to 11 by deleting '8', The editor is frozen with following text

`<maven.compiler.target>1.</maven.compiler.target>
`

**Comment by mickaelistria** [comment]
Most likely https://github.com/eclipse/lsp4e/pull/34
