### ISSUE TITLE
https://github.com/eclipse-m2e/m2e-core/issues/959

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx-maven#299]
https://github.com/eclipse-m2e/m2e-core/issues/959

**Comment by vrubezhny** [comment]
@mickaelistria  Need help in finding a similar nexus public repo I can use to test as it doesn't look like the repo mentioned in the issue https://github.com/eclipse-m2e/m2e-core/issues/959 is available for me:  `Unknown host nexus.canda.com: Name or service not known`. Any idea?

**Comment by mickaelistria** [comment]
Sorry, I have no idea. The most sustainable path forward would probably be to start an owned Nexus instance (eg with https://blog.sonatype.com/how-to-get-started-with-nexus-repository-manager-oss or using the Docker image ) and populate it with interesting content for lemminx-maven tests and use this.
It's more work though, but hopefully it will make everything easier for further maintenance.

**Comment by Renan-Di** [comment]
Any updates on the problem? Same situation here, we have an internal repo configured in a profile activated by properties inside our settings.xml.
Eclipse build and artifact resolution is fine, but trying to open pom editor rises the error(Non resolvable pom parent) or using `Maven > Select active profiles`, when closing the editor the error disapears. We are currently in version 2.2, in an older version of m2e plugin(1.6) it works fine, also deleting the file _remote.repositories causes the error to disapear until next time we redownload this artifact.

.log
```
!ENTRY org.eclipse.m2e.profiles.ui 4 0 2023-04-28 10:40:51.254
!MESSAGE Unable to open the Maven Profile selection dialog
!STACK 1
org.eclipse.core.runtime.CoreException: Could not resolve artifact com.example:super_parent_pom:pom:0.22.0
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$6(MavenImpl.java:584)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:553)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:538)
	at org.eclipse.m2e.profiles.core.internal.management.ProfileManager.resolvePomModel(ProfileManager.java:380)
	at org.eclipse.m2e.profiles.core.internal.management.ProfileManager.buildParentModel(ProfileManager.java:255)
	at org.eclipse.m2e.profiles.core.internal.management.ProfileManager.getModelHierarchy(ProfileManager.java:235)
	at org.eclipse.m2e.profiles.core.internal.management.ProfileManager.getModelHierarchy(ProfileManager.java:237)
	at org.eclipse.m2e.profiles.core.internal.management.ProfileManager.getProfileDatas(ProfileManager.java:147)
	at org.eclipse.m2e.profiles.ui.internal.actions.ProfileSelectionHandler$GetProfilesJob.getAllProfiles(ProfileSelectionHandler.java:283)
	at org.eclipse.m2e.profiles.ui.internal.actions.ProfileSelectionHandler$GetProfilesJob.run(ProfileSelectionHandler.java:199)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Contains: Missing com.example:super_parent_pom:pom:0.22.0
!SUBENTRY 1 org.eclipse.m2e.core 4 -1 2023-04-28 10:40:51.255
!MESSAGE Could not resolve artifact com.example:super_parent_pom:pom:0.22.0
!SUBENTRY 2 org.eclipse.m2e.core 4 0 2023-04-28 10:40:51.255
!MESSAGE Missing com.example:super_parent_pom:pom:0.22.0
```
