### ISSUE TITLE
RemoteCentralRepository is not functional anymore?

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/lemminx-maven#431]
A `TimeoutException` has started to appear on every try to access `search.maven.org`:

```
Jun 30, 2023 12:28:09 PM org.eclipse.lemminx.extensions.maven.searcher.RemoteCentralRepositorySearcher getResponseBody
SEVERE: Maven Central Repo search failed for com.github.gianttreelp.proguardservicesmapper:null:null
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:662)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:670)
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:154)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at org.eclipse.lemminx.extensions.maven.searcher.RemoteCentralRepositorySearcher.getResponseBody(RemoteCentralRepositorySearcher.java:208)
	at org.eclipse.lemminx.extensions.maven.searcher.RemoteCentralRepositorySearcher.internalGetGroupIds(RemoteCentralRepositorySearcher.java:129)
	at org.eclipse.lemminx.extensions.maven.searcher.RemoteCentralRepositorySearcher.getPluginGroupIds(RemoteCentralRepositorySearcher.java:88)
	at org.eclipse.lemminx.extensions.maven.participants.RemoteCentralRepoTest.testGetPluginGroupIdss(RemoteCentralRepoTest.java:183)
```
I suspect that  despite[ it's declared that there are no changes in search.maven.org API](https://central.sonatype.org/faq/what-happened-to-search-maven-org/#what-about-the-searchmavenorg-api), a possible redirect operation might take place or may require increasing of the used  timeout values, see: 

> On February 23, 2023, we started redirecting users from search.maven.org to central.sonatype.com. Launched in September of 2022, central.sonatype.com provides the main functionality of search.maven.org with enhanced search results, including security vulnerability and software quality information.
> If you discover functionality that's missing or have suggestions for things to add, we'd love to hear from you, [so create an Improvement Issue in the MVNCENTRAL project.](https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=4&pid=10302)
> [Click here to go back to search.maven.org](https://search.maven.org/?eh), and we won't redirect you back here.
> For more details on this change, please see [this FAQ on central.sonatype.org](https://central.sonatype.org/faq/what-happened-to-search-maven-org/).

**Comment by fbricon** [comment]
https://status.maven.org/ shows the search API was/is down today. It says it's fixed now, but I'm still having trouble performing requests to search.maven.org

**Comment by vrubezhny** [comment]
Well. It just started to work - JUnit tests succeeded when running locally.
