### ISSUE TITLE
NullPointerException in ProjectValidator when calling contains on activeProfiles

### ISSUE THREAD

**Issue by rgrunber** [eclipse/lemminx-maven#459]
```
SEVERE: Error while processing diagnostics for the participant 'org.eclipse.lemminx.extensions.maven.participants.diagnostics.MavenDiagnosticParticipant'.
java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because "activeprofiles" is null
	at org.eclipse.lemminx.extensions.maven.participants.diagnostics.ProjectValidator.lambda$validateManagedDependencies$8(ProjectValidator.java:182)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.eclipse.lemminx.extensions.maven.participants.diagnostics.ProjectValidator.lambda$validateManagedDependencies$9(ProjectValidator.java:180)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.eclipse.lemminx.extensions.maven.participants.diagnostics.ProjectValidator.validateManagedDependencies(ProjectValidator.java:179)
	at org.eclipse.lemminx.extensions.maven.participants.diagnostics.ProjectValidator.validateProject(ProjectValidator.java:91)
	at org.eclipse.lemminx.extensions.maven.participants.diagnostics.MavenDiagnosticParticipant.doDiagnostics(MavenDiagnosticParticipant.java:70)
	at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:67)
	at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:49)
	at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:190)
	at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:204)
	at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:716)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$new$2(XMLTextDocumentService.java:207)
	at org.eclipse.lemminx.commons.ModelValidatorDelayer.lambda$validateWithDelay$0(ModelValidatorDelayer.java:69)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

https://github.com/eclipse/lemminx-maven/blob/4943715f2116ae919f90144a773aa8dc6f073378/lemminx-maven/src/main/java/org/eclipse/lemminx/extensions/maven/participants/diagnostics/ProjectValidator.java#L182

**Comment by vrubezhny** [comment]
Thanks for reporting!
