### ISSUE TITLE
NullPointerException when clicking around in the pom file of a plugin used by a project

### ISSUE THREAD

**Issue by rgrunber** [eclipse/lemminx-maven#464]
1. Open https://github.com/eclipse/lemminx/blob/main/pom.xml
2. Go to `maven-javadoc-plugin` and "Go to definition" over that plugin definition (<kbd>ctrl</kbd> click). I should take you to the maven-javadoc-plugin pom file)
3. Start clicking within an `<properties>`, `<dependencyManagement>`, or `<dependencies>` tag.

```
Jul. 27, 2023 3:31:26 P.M. org.eclipse.lemminx.extensions.maven.participants.codeaction.ExtractPropertyCodeAction doCodeActionUnconditional
SEVERE: Cannot invoke "java.io.File.toURI()" because the return value of "org.apache.maven.project.MavenProject.getFile()" is null
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because the return value of "org.apache.maven.project.MavenProject.getFile()" is null
	at org.eclipse.lemminx.extensions.maven.participants.codeaction.ExtractPropertyCodeAction.findParentProjects(ExtractPropertyCodeAction.java:391)
	at org.eclipse.lemminx.extensions.maven.participants.codeaction.ExtractPropertyCodeAction.doCodeActionUnconditional(ExtractPropertyCodeAction.java:129)
	at org.eclipse.lemminx.services.XMLCodeActions.doCodeActions(XMLCodeActions.java:81)
	at org.eclipse.lemminx.services.XMLLanguageService.doCodeActions(XMLLanguageService.java:284)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$codeAction$24(XMLTextDocumentService.java:502)
	at org.eclipse.lemminx.commons.ModelTextDocuments.lambda$computeModelAsync$0(ModelTextDocuments.java:118)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by vrubezhny** [comment]
Thanks for reporting!
