### ISSUE TITLE
OngoingOperationException should be handled

### ISSUE THREAD

**Issue by rgrunber** [eclipse/lemminx-maven#480]
Attempting to activate completion from within `<dependencies>` (or maybe `<dependency>`).

```
Jul. 31, 2023 10:18:25 A.M. org.eclipse.lemminx.extensions.maven.participants.completion.MavenCompletionParticipant lambda$internalCollectRemoteGAVCompletion$50
SEVERE: org.eclipse.lemminx.extensions.maven.searcher.RemoteCentralRepositorySearcher$OngoingOperationException: The Maven Search 'Get Artifacts' operation is in progress for artifact: 'Dependency {groupId=org.junit.jupiter, artifactId=junit-jupiter-api, version=${junit.version}, type=jar}, packaging: 'jar'.
java.util.concurrent.ExecutionException: org.eclipse.lemminx.extensions.maven.searcher.RemoteCentralRepositorySearcher$OngoingOperationException: The Maven Search 'Get Artifacts' operation is in progress for artifact: 'Dependency {groupId=org.junit.jupiter, artifactId=junit-jupiter-api, version=${junit.version}, type=jar}, packaging: 'jar'.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at org.eclipse.lemminx.extensions.maven.participants.completion.MavenCompletionParticipant.lambda$internalCollectRemoteGAVCompletion$50(MavenCompletionParticipant.java:918)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.eclipse.lemminx.extensions.maven.participants.completion.MavenCompletionParticipant.internalCollectRemoteGAVCompletion(MavenCompletionParticipant.java:871)
	at org.eclipse.lemminx.extensions.maven.participants.completion.MavenCompletionParticipant.onXMLContent(MavenCompletionParticipant.java:417)
	at org.eclipse.lemminx.services.XMLCompletions.collectInsideContent(XMLCompletions.java:798)
	at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:260)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:171)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$completion$3(XMLTextDocumentService.java:264)
	at org.eclipse.lemminx.commons.ModelTextDocuments.lambda$computeModelAsync$0(ModelTextDocuments.java:118)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.eclipse.lemminx.extensions.maven.searcher.RemoteCentralRepositorySearcher$OngoingOperationException: The Maven Search 'Get Artifacts' operation is in progress for artifact: 'Dependency {groupId=org.junit.jupiter, artifactId=junit-jupiter-api, version=${junit.version}, type=jar}, packaging: 'jar'.
	at org.eclipse.lemminx.extensions.maven.searcher.RemoteCentralRepositorySearcher$CacheManager.getAssync(RemoteCentralRepositorySearcher.java:223)
	at org.eclipse.lemminx.extensions.maven.searcher.RemoteCentralRepositorySearcher.internalGetArtifacts(RemoteCentralRepositorySearcher.java:283)
	at org.eclipse.lemminx.extensions.maven.searcher.RemoteCentralRepositorySearcher.getArtifacts(RemoteCentralRepositorySearcher.java:257)
	at org.eclipse.lemminx.extensions.maven.participants.completion.MavenCompletionParticipant.lambda$internalCollectRemoteGAVCompletion$47(MavenCompletionParticipant.java:909)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1253)
	at java.base/java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:2237)
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1933)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	... 16 more
```

Looking at the code I see https://github.com/eclipse/lemminx-maven/blob/95989dcef5b4b94cda5636e97e338790bf3f8414/lemminx-maven/src/main/java/org/eclipse/lemminx/extensions/maven/searcher/RemoteCentralRepositorySearcher.java#L221-L226 . If the operation is in progress, I don't think there's a need to log this with the full exception. The exception should be caught and handled. Otherwise it just looks like some unexpected state (likely a bug) has occured.

**Comment by vrubezhny** [comment]
Thanks for reporting!
