### ISSUE TITLE
Error while initializing extension <org.eclipse.lemminx.extensions.relaxng.RelaxNGPlugin>

### ISSUE THREAD

**Issue by laeubi** [eclipse/lemminx-maven#551]
I currently try to build like described here: https://github.com/laeubi/lemminx-maven/blob/master/CONTRIBUTING.md

The log is all spammed with these repeated exceptions, the build succeeds but this does not look right

```
Feb. 16, 2024 6:26:21 AM org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry registerExtension
SCHWERWIEGEND: Error while initializing extension <org.eclipse.lemminx.extensions.relaxng.RelaxNGPlugin>
java.lang.SecurityException: class "com.thaiopensource.relaxng.pattern.MySchemaPatternBuilder"'s signer information does not match signer information of other classes in the same package
	at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1158)
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:902)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.eclipse.lemminx.extensions.relaxng.RelaxNGPlugin.start(RelaxNGPlugin.java:90)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.registerExtension(XMLExtensionsRegistry.java:284)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initialize(XMLExtensionsRegistry.java:270)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initializeIfNeeded(XMLExtensionsRegistry.java:255)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.getCompletionParticipants(XMLExtensionsRegistry.java:155)
	at org.eclipse.lemminx.services.XMLCompletions.getCompletionParticipants(XMLCompletions.java:1037)
	at org.eclipse.lemminx.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:691)
	at org.eclipse.lemminx.services.XMLCompletions.collectInsideContent(XMLCompletions.java:790)
	at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:227)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:171)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:166)
	at org.eclipse.lemminx.extensions.maven.participants.completion.PathWebResourcesTest.testMojoParametersDirectories(PathWebResourcesTest.java:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)

```

**Comment by angelozerr** [comment]
It is the same issue than https://github.com/eclipse/lemminx/issues/1589

**Comment by mickaelistria** [comment]
> It is the same issue than https://github.com/eclipse/lemminx/issues/1589

Indeed, an issue from upstream, nothing lemminx-maven can do here I guess.
