### ISSUE TITLE
Download artifacts from remote repositories on-demand (hover, completion, validation...)`

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx-maven#57]
When trying to validate or get assistance on some plugin or dependency that's not available in local repo and that's necessary to have locally for smart results, it should be downloaded locally so the LS would then provide smartest results.

**Comment by AObuchow** [comment]
Today while working on a side-project, one of the dependencies was unable to resolve.
m2e gave an error when running "update project" (which usually resolves pom dependencies). 
I thought it'd be worth pasting the error here as it might give insight to how m2e downloads artifacts from remote repositories:
```

Failed to read artifact descriptor for com.github.goxr3plus:java-stream-player:jar:10.0.0

org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for com.github.goxr3plus:java-stream-player:jar:10.0.0
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:255)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:530)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:515)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:403)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:356)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:344)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:247)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:279)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:169)
	at org.apache.maven.project.DefaultProjectBuilder.resolveDependencies(DefaultProjectBuilder.java:225)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:198)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:122)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.readMavenProject(MavenImpl.java:630)
	at org.eclipse.m2e.core.internal.project.registry.DefaultMavenDependencyResolver.resolveProjectDependencies(DefaultMavenDependencyResolver.java:63)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refreshPhase2(ProjectRegistryManager.java:551)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.lambda$2(ProjectRegistryManager.java:515)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:513)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:365)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:312)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:405)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:352)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1370)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:349)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:77)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to transfer com.github.goxr3plus:java-stream-player:pom:10.0.0 from https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced. Original error: Could not transfer artifact com.github.goxr3plus:java-stream-player:pom:10.0.0 from/to jitpack.io (https://jitpack.io): NullPointerException
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:423)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:225)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:202)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240)
	... 32 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Failure to transfer com.github.goxr3plus:java-stream-player:pom:10.0.0 from https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced. Original error: Could not transfer artifact com.github.goxr3plus:java-stream-player:pom:10.0.0 from/to jitpack.io (https://jitpack.io): NullPointerException
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:226)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:192)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:564)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:482)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:400)
	... 35 more
	pom.xml	/sample-manager	line 1	Maven Dependency Problem

```

**Comment by mickaelistria** [comment]
So I think we're good here, as we do set `setResolveDependencies(true)` whenever we use ProjectBuildingRequest. OK to close?

**Comment by AObuchow** [comment]
I think so (we can close), although I think it's worth trying to either set up a test if possible or try removing lines such as [this](https://github.com/eclipse/lemminx-maven/blob/master/lemminx-maven/pom.xml#L97) from the pom.xml and see if these dependencies are now resolved.

**Comment by AObuchow** [comment]
We should make sure that we have a test to download a remote artifact (both artifacts + maven plugins) from completion, diagnostics, and hover (+ maybe definition at some point?)

**Comment by AObuchow** [comment]
Some findings I've found while I've been working on tests which ensure remote artifacts are downloaded to the local repo:

1. The following artifact's jar or pom does _not_ get downloaded, although it's directory in the local repo `~/.m2/repository/org/tmatesoft/svnkit/svnkit/1.3.8` gets created:
```XML
	<dependencies>
		<dependency>
			<groupId>org.tmatesoft.svnkit</groupId>
			<artifactId>svnkit</artifactId>
			<version>1.3.8</version>
			<type>pom</type>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>soffid</id>
			<layout>m2</layout>
			<url>http://www.soffid.com/maven/</url>
		</repository>
	</repositories>
```
However, the creation of the parent directory in the local repo is not a valid indication that the artifact was downloaded. Setting the above dependency's version to a non-existent version (eg. `9.9.9`) still results in the creation of the parent directory `(~/.m2/repository/org/tmatesoft/svnkit/svnkit/9.9.9)`

This issue also occurs with [`image4j.sf.net:image4j:0.7`](http://www.soffid.com/maven/image4j/sf/net/image4j/0.7/) (and presumably other artifacts)


2. The following artifacts _pom_ **does download** to the local repository. Note that the artifact is [only packaged as a pom](http://www.soffid.com/maven/org/glassfish/jersey/project/2.19/).
```XML
	<dependencies>
	<dependency>
		<groupId>org.glassfish.jersey</groupId>
		<artifactId>project</artifactId>
		<version>2.19</version>
	</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>soffid</id>
			<layout>m2</layout>
			<url>http://www.soffid.com/maven/</url>
		</repository>
	</repositories>
```

**Comment by mickaelistria** [comment]
> The following artifact's jar or pom does not get downloaded

as far as I can see, this artifact isn't available on Central; while org.glassfish.jersey:project:2.19 is on Central. Could it be that the repositories are ignored at some places?

> although it's directory in the local repo ~/.m2/repository/org/tmatesoft/svnkit/svnkit/1.3.8 gets created

The directory is created even if unsuccessful by Maven to add some marker about the last attempt to download it.

**Comment by AObuchow** [comment]
> > The following artifact's jar or pom does not get downloaded
> 
> as far as I can see, this artifact isn't available on Central; while org.glassfish.jersey:project:2.19 is on Central. Could it be that the repositories are ignored at some places?
> 

That's a very good clue. Perhaps the `soffid` repo is being ignored and central is being used.

> > although it's directory in the local repo ~/.m2/repository/org/tmatesoft/svnkit/svnkit/1.3.8 gets created
> 
> The directory is created even if unsuccessful by Maven to add some marker about the last attempt to download it.

I noticed with m2e "update project", a .lastUpdated gets created which is from MavenResolver. This would be the marker.
In LemMinX, it seems this .lastUpdated isn't being created on hover (just an observation).

I just tested out m2e's "update project" on some of the artifacts that aren't being downloaded in LemMinX (as mentioned above). It seems that m2e is unable to download these artifacts either.

**Comment by mickaelistria** [comment]
> I just tested out m2e's "update project" on some of the artifacts that aren't being downloaded in LemMinX (as mentioned above). It seems that m2e is unable to download these artifacts either.

Ok... So maybe the soffid repo is the cause of some issues.
Unless there are still some known cases or pending work, I suggest we close this issue and open newer, more focused, ones for future cases.

**Comment by AObuchow** [comment]
Ok sounds good. 
If there are other maven repositories that contain an index that we come across, we should try them out for downloading remote artifacts. 

I will try to finish the tests I was writing and close this when the tests are merged.

**Comment by AObuchow** [comment]
@mickaelistria I currently have a test for hovering on an artifact id & downloading the dependency.

However, while writing tests for this topic, I realized the scope of the issue should probably be defined a bit further.
Which cases of completion, hover and diagnostic should cause artifact downloads?
Should it be:
- All cases (when hover/completion is called, try to find if the node is a child of a dependency or plugin node)
- Plugin configuration
- GAV completion
- Something else

I think the "All cases" approach might be best, in which case I'd close this bug and open a new one for that topic.

**Comment by mickaelistria** [comment]
I agree for all cases.

**Comment by AObuchow** [comment]
> I agree for all cases.

New bug: https://github.com/eclipse/lemminx-maven/issues/105

Also stemming from this discussion: https://github.com/eclipse/lemminx-maven/issues/104
